services:
  - type: web
    name: autonote
    env: python
    region: oregon
    plan: starter  # Upgraded from free for better performance
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2 --max-requests 200
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard
    disk:
      name: cache
      mountPath: /opt/render/project/.cache
      sizeGB: 1  
