import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from docx import Document
from docx.shared import Inches

def save_as_txt(notes: str, file_id: str, output_dir: str) -> str:
    """Save notes as plain text file"""
    filename = f"{file_id}.txt"
    filepath = os.path.join(output_dir, filename)
    
    os.makedirs(output_dir, exist_ok=True)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(notes)
    
    return filepath

def save_as_md(notes: str, file_id: str, output_dir: str) -> str:
    """Save notes as Markdown file"""
    filename = f"{file_id}.md"
    filepath = os.path.join(output_dir, filename)
    
    os.makedirs(output_dir, exist_ok=True)
    
    # Format as markdown with proper headers
    md_content = f"# Generated Notes\n\n{notes}\n\n---\n*Generated by autonote*"
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(md_content)
    
    return filepath

def save_as_pdf(notes: str, file_id: str, output_dir: str) -> str:
    """Save notes as PDF file using reportlab"""
    filename = f"{file_id}.pdf"
    filepath = os.path.join(output_dir, filename)
    
    os.makedirs(output_dir, exist_ok=True)
    
    # Create PDF document
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    # Add title
    title = Paragraph("Generated Notes", styles['Title'])
    story.append(title)
    story.append(Spacer(1, 12))
    
    # Add notes content
    # Split notes into paragraphs for better formatting
    paragraphs = notes.split('\n')
    for para in paragraphs:
        if para.strip():
            p = Paragraph(para, styles['Normal'])
            story.append(p)
            story.append(Spacer(1, 6))
    
    # Add footer
    story.append(Spacer(1, 12))
    footer = Paragraph("<i>Generated by autonote</i>", styles['Italic'])
    story.append(footer)
    
    doc.build(story)
    return filepath

def save_as_docx(notes: str, file_id: str, output_dir: str) -> str:
    """Save notes as DOCX file"""
    filename = f"{file_id}.docx"
    filepath = os.path.join(output_dir, filename)
    
    os.makedirs(output_dir, exist_ok=True)
    
    # Create document
    doc = Document()
    
    # Add title
    title = doc.add_heading('Generated Notes', 0)
    
    # Add notes content
    paragraphs = notes.split('\n')
    for para in paragraphs:
        if para.strip():
            doc.add_paragraph(para)
    
    # Add footer
    doc.add_paragraph()
    footer_para = doc.add_paragraph('Generated by autonote')
    footer_run = footer_para.runs[0]
    footer_run.italic = True
    
    doc.save(filepath)
    return filepath
