import os
from .online_ai import generate_notes_online

def simple_text_summarizer(text: str) -> str:
    """Enhanced fallback summarizer without AI dependencies"""
    if not text or not text.strip():
        return "**No Content Available**\n\n---\n\n*No text content was found.*"
    
    # Create structured notes even without AI
    lines = []
    lines.append("# **STUDY NOTES**")
    lines.append("=" * 50)
    lines.append("")
    
    sentences = text.strip().split('.')
    
    # Overview
    if len(text) > 200:
        lines.append("## **OVERVIEW**")
        overview = text[:300] + "..." if len(text) > 300 else text[:300]
        lines.append(overview)
        lines.append("")
    
    # Key points
    lines.append("## **KEY POINTS**")
    
    if len(sentences) <= 3:
        lines.append(f"• {text.strip()}")
    else:
        # Extract meaningful sentences
        key_sentences = []
        for sentence in sentences:
            cleaned = sentence.strip()
            if 20 <= len(cleaned) <= 200:  # Good length sentences
                key_sentences.append(cleaned)
        
        # Take best sentences
        selected = key_sentences[:6] if key_sentences else sentences[:3]
        for sentence in selected:
            if sentence.strip():
                lines.append(f"• {sentence.strip()}")
    
    lines.append("")
    lines.append("## **SUMMARY**")
    
    if len(sentences) >= 2:
        summary = f"{sentences[0].strip()}. {sentences[-1].strip()}."
    else:
        summary = text[:200] + "..." if len(text) > 200 else text
    
    lines.append(summary)
    lines.append("")
    lines.append("---")
    lines.append("*Generated by AutoNote (Simple Mode)*")
    
    return "\n".join(lines)

def generate_notes(text: str, note_style: str = "structured") -> str:
    """Generate comprehensive structured notes from text using online AI"""
    # Try online AI first (primary method)
    try:
        return generate_notes_online(text, note_type=note_style)
    except Exception as ai_error:
        print(f"Online AI failed: {ai_error}")
    
    # Fallback to enhanced simple summarizer
    return simple_text_summarizer(text)
